CREATE TABLE IF NOT EXISTS `bmwiderruf` (
    `OXID`       CHAR(32)        NOT NULL,
    `OXSHOPID`   INT(11)         NOT NULL DEFAULT 1,
    `OXORDERID`  CHAR(32)        NOT NULL DEFAULT '',
    `OXORDERNR`  INT(11)         NOT NULL DEFAULT 0,
    `OXEMAIL`    VARCHAR(255)    NOT NULL DEFAULT '',
    `OXMESSAGE`  TEXT            NOT NULL,
    `OXIP`       VARCHAR(45)     NOT NULL DEFAULT '',
    `OXCREATED`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`OXID`),
    KEY `OXORDERID` (`OXORDERID`),
    KEY `OXORDERNR` (`OXORDERNR`),
    KEY `OXEMAIL`   (`OXEMAIL`),
    KEY `OXCREATED` (`OXCREATED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Widerruf-Anfragen (Kunden-Submissions /widerruf)';
